version: '3'

services:
  todo_list_php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - todo_list_network

  todo_list_server:
    image: nginx:alpine
    ports:
      - "8989:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - todo_list_network

  product_manager_db:
    image: mysql:8.0
    container_name: todo_list_db
    ports:
      - "3301:3306"
    volumes:
      - .data/mysql:/var/lib/mysql
    command: --max_allowed_packet=67108864
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      - todo_list_network

networks:
  todo_list_network:
    driver: bridge
